name: sync_up
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Updated to a more flexible range

dependencies:
  flutter:
    sdk: flutter

  # UI & UX Packages
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.1
  country_code_picker: ^3.0.0

  # Firebase Packages (Latest Stable & Compatible Versions)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # OAuth Packages
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4

  shared_preferences: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/logos/
