// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44E5qGnyul7rm18DOqDMXPDCnO_PB2vE',
    appId: '1:792629822847:web:a03e0e1704b97505ed864a',
    messagingSenderId: '792629822847',
    projectId: 'syncup-social-app-2025',
    authDomain: 'syncup-social-app-2025.firebaseapp.com',
    storageBucket: 'syncup-social-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5j4AHJnHyBUjHMSXVNxPQb-eG2JaZ-cY',
    appId: '1:792629822847:android:94573d2c80018eafed864a',
    messagingSenderId: '792629822847',
    projectId: 'syncup-social-app-2025',
    storageBucket: 'syncup-social-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79iLGDO7VlC5tJ7_3MOfnFQRz0dq_XLo',
    appId: '1:792629822847:ios:fc99a1077f171684ed864a',
    messagingSenderId: '792629822847',
    projectId: 'syncup-social-app-2025',
    storageBucket: 'syncup-social-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.syncUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB79iLGDO7VlC5tJ7_3MOfnFQRz0dq_XLo',
    appId: '1:792629822847:ios:fc99a1077f171684ed864a',
    messagingSenderId: '792629822847',
    projectId: 'syncup-social-app-2025',
    storageBucket: 'syncup-social-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.syncUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB44E5qGnyul7rm18DOqDMXPDCnO_PB2vE',
    appId: '1:792629822847:web:44cc8a6e61559844ed864a',
    messagingSenderId: '792629822847',
    projectId: 'syncup-social-app-2025',
    authDomain: 'syncup-social-app-2025.firebaseapp.com',
    storageBucket: 'syncup-social-app-2025.firebasestorage.app',
  );
}
