// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFyw1_gOdX_lkC_IlpFB3kW74mWn6ePo',
    appId: '1:732949162701:web:24d100dac1532084711784',
    messagingSenderId: '732949162701',
    projectId: 'sync-up-43399',
    authDomain: 'sync-up-43399.firebaseapp.com',
    storageBucket: 'sync-up-43399.firebasestorage.app',
    measurementId: 'G-KKXLHRMFGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBac3LBkSLHLKWjNRaK5oDRVqApSZ_UY2w',
    appId: '1:732949162701:android:7d8d531eeac5cb43711784',
    messagingSenderId: '732949162701',
    projectId: 'sync-up-43399',
    storageBucket: 'sync-up-43399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2hCg4CXxWgmvusrtqvHwxPsvkcb3JkM',
    appId: '1:732949162701:ios:603d3ed8ac80ddce711784',
    messagingSenderId: '732949162701',
    projectId: 'sync-up-43399',
    storageBucket: 'sync-up-43399.firebasestorage.app',
    iosBundleId: 'com.example.syncUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT2hCg4CXxWgmvusrtqvHwxPsvkcb3JkM',
    appId: '1:732949162701:ios:603d3ed8ac80ddce711784',
    messagingSenderId: '732949162701',
    projectId: 'sync-up-43399',
    storageBucket: 'sync-up-43399.firebasestorage.app',
    iosBundleId: 'com.example.syncUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFyw1_gOdX_lkC_IlpFB3kW74mWn6ePo',
    appId: '1:732949162701:web:3b9499ce43eae200711784',
    messagingSenderId: '732949162701',
    projectId: 'sync-up-43399',
    authDomain: 'sync-up-43399.firebaseapp.com',
    storageBucket: 'sync-up-43399.firebasestorage.app',
    measurementId: 'G-GECG1PFE8J',
  );
}
